name: Long Trail

on:
  schedule:
    - cron: "0 19 * * 1-5"
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node it
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          ref: ${{ github.head_ref }}
      - name: Install it
        run: npm install
      - name: Config it
        run: |
          echo TWITTER_APP_KEY_lt=${{ secrets.TWITTER_APP_KEY_LT }} > .env
          echo TWITTER_APP_SECRET_lt=${{ secrets.TWITTER_APP_SECRET_LT }} >> .env
          echo TWITTER_ACCESS_TOKEN_lt=${{ secrets.TWITTER_ACCESS_TOKEN_LT }} >> .env
          echo TWITTER_ACCESS_SECRET_lt=${{ secrets.TWITTER_ACCESS_SECRET_LT }} >> .env
      - name: Tweet it
        run: node dist/scripts/tweet_a_mile.js lt
      - name: Commit it
        run: |
          git config --global user.name 'Bill Morris'
          git config --global user.email 'bill@billmorris.io'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Tweeted Long Trail"
          git push
